// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyQtG32EGFlVks8ErgfIKVIPrmjx2oXN8',
    appId: '1:356730112455:web:b838fb34efb83d945db1e2',
    messagingSenderId: '356730112455',
    projectId: 'wni-db',
    authDomain: 'wni-db.firebaseapp.com',
    databaseURL: 'https://wni-db-default-rtdb.firebaseio.com',
    storageBucket: 'wni-db.appspot.com',
    measurementId: 'G-GE0SMRQCL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsaYGE72Koa9ojv3chBYBkWxaoRub0TNo',
    appId: '1:356730112455:android:b35d8fd84668014b5db1e2',
    messagingSenderId: '356730112455',
    projectId: 'wni-db',
    databaseURL: 'https://wni-db-default-rtdb.firebaseio.com',
    storageBucket: 'wni-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsQshLyuo8soaQFo9uKR69bIy_IIxkPNk',
    appId: '1:356730112455:ios:9df9ade19c18390e5db1e2',
    messagingSenderId: '356730112455',
    projectId: 'wni-db',
    databaseURL: 'https://wni-db-default-rtdb.firebaseio.com',
    storageBucket: 'wni-db.appspot.com',
    iosBundleId: 'com.example.projectApkUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsQshLyuo8soaQFo9uKR69bIy_IIxkPNk',
    appId: '1:356730112455:ios:9df9ade19c18390e5db1e2',
    messagingSenderId: '356730112455',
    projectId: 'wni-db',
    databaseURL: 'https://wni-db-default-rtdb.firebaseio.com',
    storageBucket: 'wni-db.appspot.com',
    iosBundleId: 'com.example.projectApkUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyQtG32EGFlVks8ErgfIKVIPrmjx2oXN8',
    appId: '1:356730112455:web:1da46399fe855d015db1e2',
    messagingSenderId: '356730112455',
    projectId: 'wni-db',
    authDomain: 'wni-db.firebaseapp.com',
    databaseURL: 'https://wni-db-default-rtdb.firebaseio.com',
    storageBucket: 'wni-db.appspot.com',
    measurementId: 'G-E4YGP926RC',
  );
}
